// Trampoline for calling MLIR ciface functions with arbitrary arity.
// All args are pointer-sized: first is output ptr, rest are input ptrs.
// On x86_64 SysV ABI, first 6 args go in registers (rdi, rsi, rdx, rcx, r8, r9),
// remaining args go on the stack. This function just pushes all args and calls.
//
// We use a variadic-like approach: cast fn to (void (*)(void *, void **, int))
// and let the wrapper push args.

#include <stdint.h>

// Generic: fn(output, args_array, n_args)
// Assumes fn takes (void *out, void *in0, void *in1, ...)
void call_mlir_kernel(void (*fn)(), void *out, void **args, int n_inputs) {
    // We can't dynamically call with variable args in C without libffi.
    // But we know the max arity we support: up to ~300.
    // For each specific arity, cast to the correct function type.
    // Since this is compiled separately, we don't need Rust's type system.
    
    // Use a union of function pointers to handle different arities
    // The actual call is done via inline assembly to avoid C calling
    // convention limitations with >6 args on x86_64.
    
    // On x86_64 SysV: args go in rdi, rsi, rdx, rcx, r8, r9, then stack
    // We want: rdi=out, rsi=args[0], rdx=args[1], rcx=args[2], 
    //          r8=args[3], r9=args[4], then push args[5..n_inputs-1]
    
    // Build a stack array with all args (out + inputs)
    // On the stack: [out_ptr, in0_ptr, in1_ptr, ...]
    // We'll use a jmp-based trampoline that sets up the args and calls fn.
    
    // Simple approach: use assembly to set up the call
    // This is a self-modifying approach — we write the call instruction
    // with the right number of args at runtime.
    
    // Actually the simplest: since the x86_64 calling convention is stable
    // for pointer args, we just push all args in reverse order and call.
    // Extra args beyond what the function expects are harmless on x86_64
    // (they just take up stack space but are not accessed).
    
    // So we call the function with a FIXED number of args (all 300 args)
    // but only the first n_inputs+1 are meaningful. The function reads
    // exactly its declared args, ignoring extra stack data.
    // This works because x86_64 doesn't pop extra args — the callee
    // just doesn't reference stack slots beyond its declared args.
    
    // WRONG: MLIR's ciface functions are NOT variadic. The exact arity
    // is part of the function signature. We can't call with more args
    // than declared.
    
    // Correct approach: generate the call with the exact arity.
    // We use a known max arity (300) and only pass the right number.
    // This requires a per-arity wrapper, but we only need it up to 300.
    
    // For now we use libffi-style but inline:
    // Build the argument list on the stack and use assembly to call.
    // x86_64: args go in registers (first 6) then stack (rest).
    
    // Since we can't write the call dynamically in C, we use a generated
    // switch statement. The switch is compiled once for the max arity.
    // This is generated by the build.rs script.
}
