"""Boilerplate Rust template constants for HAL CPU op implementations.

Contains shared scaffolding: header, shape metadata, BLAS extern declaration,
and cache stub functions.
"""

from __future__ import annotations

HEADER = """\
//! Auto-generated by EmitRust. Do not edit.
//! Source: hal_ir.json for {model_name}
//!
//! Scalar CPU implementations of all HAL ops used in this model.
//! Optimisations (rayon, loop fusion, vectorisation) belong in Phase C.

#![allow(unused_variables, dead_code)]
"""

OP_SHAPE_META = """\
/// Shape metadata for HAL CPU operations.
///
/// Carries runtime shape information that isn't available at compile time
/// (dynamic batch/seq dimensions) and op-specific attributes (kind, value).
#[derive(Debug, Clone)]
pub struct OpShapeMeta {
    pub input_shapes: Vec<Vec<i64>>,
    pub output_shape: Vec<i64>,
    pub kind: Option<String>,
    pub value: Option<f64>,
}

impl OpShapeMeta {
    pub fn new(input_shapes: Vec<Vec<i64>>, output_shape: Vec<i64>) -> Self {
        Self { input_shapes, output_shape, kind: None, value: None }
    }
}
"""

BLAS_EXTERN = """\
// ── Accelerate BLAS (cblas_sgemm) ──
// Linked via build.rs (macOS: Accelerate framework, Linux: openblas).

#[cfg(target_os = "macos")]
#[link(name = "Accelerate", kind = "framework")]
extern "C" {
    fn cblas_sgemm(
        order: i32, transA: i32, transB: i32,
        m: i32, n: i32, k: i32,
        alpha: f32, a: *const f32, lda: i32,
        b: *const f32, ldb: i32,
        beta: f32, c: *mut f32, ldc: i32,
    );
}

#[cfg(not(target_os = "macos"))]
extern "C" {
    fn cblas_sgemm(
        order: i32, transA: i32, transB: i32,
        m: i32, n: i32, k: i32,
        alpha: f32, a: *const f32, lda: i32,
        b: *const f32, ldb: i32,
        beta: f32, c: *mut f32, ldc: i32,
    );
}

const CBLAS_ROW_MAJOR: i32 = 101;
const CBLAS_NO_TRANS: i32 = 111;
const CBLAS_TRANS: i32 = 112;
"""

STUB_CACHE = """\
// ── Cache stubs (Runtime-level ops, not CPU kernels) ──

pub fn cache_read_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    // Handled by Runtime (block_manager / kv_cache).
    // CPU kernel should never see cache_read — it is a HAL-level
    // operation injected by the compiler for KV cache integration.
    Ok(())
}

pub fn cache_write_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    // Handled by Runtime (block_manager / kv_cache).
    Ok(())
}
"""
