"""EmitRust backend — generate hal_ops_cpu.rs from hal_ir.json.

Reads a compiled model's ``hal_ir.json``, collects all unique op types,
and emits a self-contained Rust source file with naive scalar CPU
implementations for each op type.

Usage::

    from compiler.mlir_dialect.hal_ir.emit_rust import emit_rust

    path = emit_rust("compiled/opt_125m_kv/hal_ir.json")
    print(f"Generated: {path}")
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

_log = logging.getLogger(__name__)

# ── Template chunks ──────────────────────────────────────────────────────

HEADER = """\
//! Auto-generated by EmitRust. Do not edit.
//! Source: hal_ir.json for {model_name}
//!
//! Scalar CPU implementations of all HAL ops used in this model.
//! Optimisations (rayon, loop fusion, vectorisation) belong in Phase C.

#![allow(unused_variables, dead_code)]
"""

OP_SHAPE_META = """\
/// Shape metadata for HAL CPU operations.
///
/// Carries runtime shape information that isn't available at compile time
/// (dynamic batch/seq dimensions) and op-specific attributes (kind, value).
#[derive(Debug, Clone)]
pub struct OpShapeMeta {
    pub input_shapes: Vec<Vec<i64>>,
    pub output_shape: Vec<i64>,
    pub kind: Option<String>,
    pub value: Option<f64>,
}

impl OpShapeMeta {
    pub fn new(input_shapes: Vec<Vec<i64>>, output_shape: Vec<i64>) -> Self {
        Self { input_shapes, output_shape, kind: None, value: None }
    }
}
"""

BLAS_EXTERN = """\
// ── Accelerate BLAS (cblas_sgemm) ──
// Linked via build.rs (macOS: Accelerate framework, Linux: openblas).

#[cfg(target_os = "macos")]
#[link(name = "Accelerate", kind = "framework")]
extern "C" {
    fn cblas_sgemm(
        order: i32, transA: i32, transB: i32,
        m: i32, n: i32, k: i32,
        alpha: f32, a: *const f32, lda: i32,
        b: *const f32, ldb: i32,
        beta: f32, c: *mut f32, ldc: i32,
    );
}

#[cfg(not(target_os = "macos"))]
extern "C" {
    fn cblas_sgemm(
        order: i32, transA: i32, transB: i32,
        m: i32, n: i32, k: i32,
        alpha: f32, a: *const f32, lda: i32,
        b: *const f32, ldb: i32,
        beta: f32, c: *mut f32, ldc: i32,
    );
}

const CBLAS_ROW_MAJOR: i32 = 101;
const CBLAS_NO_TRANS: i32 = 111;
const CBLAS_TRANS: i32 = 112;
"""

STUB_CACHE = """\
// ── Cache stubs (Runtime-level ops, not CPU kernels) ──

pub fn cache_read_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    // Handled by Runtime (block_manager / kv_cache).
    // CPU kernel should never see cache_read — it is a HAL-level
    // operation injected by the compiler for KV cache integration.
    Ok(())
}

pub fn cache_write_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    // Handled by Runtime (block_manager / kv_cache).
    Ok(())
}
"""

# ── Op implementations (one per type) ────────────────────────────────────

OP_MATMUL = """\
// ── matmul ──────────────────────────────────────────────────────────

pub fn matmul_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    let a = inputs[0];
    let b = inputs[1];

    let a_shape = shape_meta.input_shapes.get(0)
        .ok_or_else(|| "matmul: missing input shape 0".to_string())?;
    let b_shape = shape_meta.input_shapes.get(1)
        .ok_or_else(|| "matmul: missing input shape 1".to_string())?;

    if a_shape.len() < 2 || b_shape.len() < 2 {
        return Err(format!(
            "matmul: expected rank >= 2, got a={:?} b={:?}",
            a_shape, b_shape,
        ));
    }

    let m = a_shape[a_shape.len() - 2] as i32;
    let k = a_shape[a_shape.len() - 1] as i32;
    let n = b_shape[b_shape.len() - 1] as i32;

    if k == 0 || m == 0 || n == 0 {
        return Ok(());
    }

    // Row-major: A[M,K] @ B[K,N] = C[M,N]
    // lda = K, ldb = N, ldc = N
    let lda = k;
    let ldb = n;
    let ldc = n;

    unsafe {
        cblas_sgemm(
            CBLAS_ROW_MAJOR,   // order
            CBLAS_NO_TRANS,    // transA
            CBLAS_NO_TRANS,    // transB
            m, n, k,           // M, N, K
            1.0,               // alpha
            a.as_ptr(), lda,   // A, lda
            b.as_ptr(), ldb,   // B, ldb
            0.0,               // beta
            output.as_mut_ptr(), ldc, // C, ldc
        );
    }

    Ok(())
}
"""

OP_ELEMENT_WISE = """\
// ── element_wise ────────────────────────────────────────────────────

pub fn element_wise_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    match shape_meta.kind.as_deref() {
        Some("add") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = a + b;
            }
        }
        Some("sub") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = a - b;
            }
        }
        Some("mul") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = a * b;
            }
        }
        Some("div") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = a / b;
            }
        }
        Some("relu") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                *o = if a > 0.0 { a } else { 0.0 };
            }
        }
        Some("rsqrt") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                *o = 1.0 / a.sqrt();
            }
        }
        Some("silu") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                // SiLU(x) = x * sigmoid(x)
                // sigmoid(x) = 1 / (1 + exp(-x))
                let sig = 1.0 / ((-a).exp() + 1.0);
                *o = a * sig;
            }
        }
        Some("gelu") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                // GELU(x) = 0.5 * x * (1 + tanh(sqrt(2/pi) * (x + 0.044715 * x^3)))
                let x3 = a * a * a;
                let inner = (0.7978845608028654 * (a + 0.044715 * x3)).tanh();
                *o = 0.5 * a * (1.0 + inner);
            }
        }
        Some("neg") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                *o = -a;
            }
        }
        Some("exp") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                *o = a.exp();
            }
        }
        Some("tanh") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                *o = a.tanh();
            }
        }
        Some("sqrt") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                *o = a.sqrt();
            }
        }
        Some("sigmoid") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                *o = 1.0 / (1.0 + (-a).exp());
            }
        }
        Some("cos") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                *o = a.cos();
            }
        }
        Some("sin") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                *o = a.sin();
            }
        }
        Some("softplus") => {
            for (o, &a) in output.iter_mut().zip(inputs[0].iter()) {
                // softplus(x) = ln(1 + exp(x))
                *o = (1.0 + a.exp()).ln();
            }
        }
        Some("pow") => {
            // pow is binary: inputs[0]^inputs[1]
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = a.powf(b);
            }
        }
        Some("max") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = a.max(b);
            }
        }
        other => {
            return Err(format!(
                "element_wise: unimplemented kind {:?}",
                other,
            ));
        }
    }
    Ok(())
}
"""

OP_SOFTMAX = """\
// ── softmax ─────────────────────────────────────────────────────────

pub fn softmax_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    let inp = inputs[0];

    // Determine last dimension size from output_shape or input_shapes.
    let last_dim = shape_meta
        .output_shape
        .last()
        .copied()
        .or_else(|| shape_meta.input_shapes.get(0)?.last().copied())
        .ok_or_else(|| "softmax: cannot determine last dimension".to_string())? as usize;

    if last_dim == 0 {
        return Ok(());
    }

    let n = inp.len();
    for chunk in output.chunks_mut(last_dim) {
        // Find max for numerical stability
        let max_val = chunk
            .iter()
            .cloned()
            .fold(f32::NEG_INFINITY, |a, b| a.max(b));

        // Compute exp and sum
        let mut sum = 0.0f32;
        for v in chunk.iter_mut() {
            let e = (*v - max_val).exp();
            *v = e;
            sum += e;
        }

        // Normalize
        let inv_sum = 1.0 / sum;
        for v in chunk.iter_mut() {
            *v *= inv_sum;
        }
    }

    Ok(())
}
"""

OP_RESHAPE = """\
// ── reshape (metadata only — flat copy) ────────────────────────────

pub fn reshape_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    let inp = inputs[0];
    if inp.len() != output.len() {
        return Err(format!(
            "reshape: element count mismatch: input {} != output {}",
            inp.len(),
            output.len(),
        ));
    }
    output.copy_from_slice(inp);
    Ok(())
}
"""

OP_TRANSPOSE = """\
// ── transpose (generic nd transpose) ───────────────────────────────

pub fn transpose_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    let inp = inputs[0];
    let input_shape = shape_meta.input_shapes.get(0)
        .ok_or_else(|| "transpose: missing input shape".to_string())?;
    let output_shape = &shape_meta.output_shape;

    let rank = input_shape.len();
    if rank < 2 {
        return Err(format!("transpose: expected rank >= 2, got {}", rank));
    }

    // The permutation is stored in shape_meta.kind as "dim1,dim2" or we
    // default to swapping the last two dimensions (common for attention).
    let perm: Vec<usize> = if let Some(kind) = &shape_meta.kind {
        kind.split(',')
            .filter_map(|s| s.trim().parse::<usize>().ok())
            .collect()
    } else {
        // Default: swap last two dims
        let mut p: Vec<usize> = (0..rank).collect();
        let last = rank - 1;
        p.swap(last - 1, last);
        p
    };

    if perm.len() != rank {
        return Err(format!(
            "transpose: permutation length {} != rank {}",
            perm.len(),
            rank,
        ));
    }

    // Precompute strides for input
    let mut in_strides: Vec<usize> = vec![1; rank];
    for i in (0..rank - 1).rev() {
        in_strides[i] = in_strides[i + 1] * input_shape[i + 1] as usize;
    }

    // Precompute strides for output
    let mut out_strides: Vec<usize> = vec![1; rank];
    for i in (0..rank - 1).rev() {
        out_strides[i] = out_strides[i + 1] * output_shape[i + 1] as usize;
    }

    // Iterate over flat output and compute source index
    for flat_idx in 0..output.len() {
        // Compute output n-dimensional index
        let mut idx = flat_idx;
        let mut o_idx = vec![0usize; rank];
        for d in 0..rank {
            o_idx[d] = idx / out_strides[d];
            idx %= out_strides[d];
        }

        // Map to input index via inverse permutation
        let mut i_idx = vec![0usize; rank];
        for d in 0..rank {
            i_idx[perm[d]] = o_idx[d];
        }

        // Compute flat input index
        let in_flat: usize = i_idx
            .iter()
            .zip(in_strides.iter())
            .map(|(&i, &s)| i * s)
            .sum();

        output[flat_idx] = inp[in_flat];
    }

    Ok(())
}
"""

OP_REDUCE = """\
// ── reduce ──────────────────────────────────────────────────────────

pub fn reduce_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    let inp = inputs[0];
    let input_shape = shape_meta.input_shapes.get(0)
        .ok_or_else(|| "reduce: missing input shape".to_string())?;
    let output_shape = &shape_meta.output_shape;

    let kind = shape_meta.kind.as_deref().unwrap_or("sum");

    // Determine reduction axis and sizes.
    // If output rank < input rank, find the reduced dim.
    // If output rank == input rank and last dim == 1, reduce last dim.
    if output_shape.len() == input_shape.len() {
        // Same rank — one dimension is reduced to 1.
        let reduce_dim = input_shape
            .iter()
            .zip(output_shape.iter())
            .position(|(&i, &o)| i != o && o == 1)
            .unwrap_or(input_shape.len() - 1);

        let outer: usize = input_shape[..reduce_dim].iter().map(|&d| d as usize).product();
        let reduce_size: usize = input_shape[reduce_dim] as usize;
        let inner: usize = input_shape[reduce_dim + 1..].iter().map(|&d| d as usize).product();

        for oi in 0..outer {
            for ii in 0..inner {
                let base = oi * reduce_size * inner + ii;
                let sum: f32 = (0..reduce_size)
                    .map(|r| inp[base + r * inner])
                    .sum();
                let out_idx = oi * inner + ii;
                if kind == "mean" {
                    output[out_idx] = sum / reduce_size as f32;
                } else {
                    output[out_idx] = sum;
                }
            }
        }
    } else {
        // Full reduction to scalar
        let sum: f32 = inp.iter().copied().sum();
        if kind == "mean" {
            output[0] = sum / inp.len() as f32;
        } else {
            output[0] = sum;
        }
    }

    Ok(())
}
"""

OP_GATHER = """\
// ── gather (embedding / indexed load) ──────────────────────────────

pub fn gather_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    let weight_table = inputs[0];

    let weight_shape = shape_meta.input_shapes.get(0)
        .ok_or_else(|| "gather: missing weight shape".to_string())?;
    let indices_shape = shape_meta.input_shapes.get(1)
        .ok_or_else(|| "gather: missing indices shape".to_string())?;

    if weight_shape.len() < 1 {
        return Err("gather: weight must be rank >= 1".to_string());
    }

    let vocab_size = weight_shape[0] as usize;
    let embed_dim: usize = weight_shape.iter().skip(1).map(|&d| d as usize).product();

    // Indices are stored as f32 in the flat buffer, but logically are i64 or i32.
    // Reinterpret the bytes.
    let indices_bytes = inputs[1].len() * 4; // f32 size
    let num_indices = indices_bytes / 8; // i64 size
    let indices: &[i64] = unsafe {
        std::slice::from_raw_parts(inputs[1].as_ptr() as *const i64, num_indices)
    };

    let num_output = output.len();
    let expected = num_indices * embed_dim;
    if num_output != expected {
        return Err(format!(
            "gather: output len {} != indices {} * embed_dim {}",
            num_output, num_indices, embed_dim,
        ));
    }

    for (i, &idx) in indices.iter().enumerate() {
        let src_start = (idx as usize) * embed_dim;
        let dst_start = i * embed_dim;
        if src_start + embed_dim > weight_table.len() {
            return Err(format!(
                "gather: index {} out of bounds (vocab_size={})",
                idx, vocab_size,
            ));
        }
        output[dst_start..dst_start + embed_dim]
            .copy_from_slice(&weight_table[src_start..src_start + embed_dim]);
    }

    Ok(())
}
"""

OP_FILL = """\
// ── fill (splat constant / arange) ─────────────────────────────────

pub fn fill_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    match shape_meta.kind.as_deref() {
        Some("arange") => {
            for (i, o) in output.iter_mut().enumerate() {
                *o = i as f32;
            }
        }
        _ => {
            let value = shape_meta.value.unwrap_or(1.0) as f32;
            output.fill(value);
        }
    }
    Ok(())
}
"""

OP_SHAPE_OF = """\
// ── shape_of ───────────────────────────────────────────────────────

pub fn shape_of_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    let input_shape = shape_meta.input_shapes.get(0)
        .ok_or_else(|| "shape_of: missing input shape".to_string())?;

    if output.len() != input_shape.len() {
        return Err(format!(
            "shape_of: output len {} != input rank {}",
            output.len(),
            input_shape.len(),
        ));
    }

    for (i, &dim) in input_shape.iter().enumerate() {
        output[i] = dim as f32;
    }
    Ok(())
}
"""

OP_SLICE = """\
// ── slice ───────────────────────────────────────────────────────────

pub fn slice_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    let inp = inputs[0];
    let input_shape = shape_meta.input_shapes.get(0)
        .ok_or_else(|| "slice: missing input shape".to_string())?;
    let output_shape = &shape_meta.output_shape;

    if input_shape.is_empty() {
        return Err("slice: empty input shape".to_string());
    }

    // Determine slice dimension from shape delta.
    // The sliced dimension has input_size > output_size.
    // We copy a contiguous sub-tensor.
    let slice_dim = input_shape
        .iter()
        .zip(output_shape.iter())
        .position(|(&i, &o)| i != o)
        .unwrap_or(0);

    let outer: usize = input_shape[..slice_dim].iter().map(|&d| d as usize).product();
    let slice_size: usize = output_shape[slice_dim] as usize;
    let inner: usize = input_shape[slice_dim + 1..].iter().map(|&d| d as usize).product();

    let src_stride = inner * input_shape[slice_dim] as usize;
    let dst_stride = inner * slice_size;

    for i in 0..outer {
        let src_base = i * src_stride;
        let dst_base = i * dst_stride;
        for j in 0..slice_size {
            let src_off = src_base + j * inner;
            let dst_off = dst_base + j * inner;
            for k in 0..inner {
                output[dst_off + k] = inp[src_off + k];
            }
        }
    }

    Ok(())
}
"""

OP_UNSQUEEZE = """\
// ── unsqueeze (metadata only — flat copy) ─────────────────────────

pub fn unsqueeze_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    let inp = inputs[0];
    if inp.len() != output.len() {
        return Err(format!(
            "unsqueeze: element count mismatch: input {} != output {}",
            inp.len(),
            output.len(),
        ));
    }
    output.copy_from_slice(inp);
    Ok(())
}
"""

OP_COMPARE = """\
// ── compare ────────────────────────────────────────────────────────

pub fn compare_cpu(
    inputs: &[&[f32]],
    output: &mut [f32],
    shape_meta: &OpShapeMeta,
) -> Result<(), String> {
    match shape_meta.kind.as_deref() {
        Some("le") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = if a <= b { 1.0 } else { 0.0 };
            }
        }
        Some("lt") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = if a < b { 1.0 } else { 0.0 };
            }
        }
        Some("gt") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = if a > b { 1.0 } else { 0.0 };
            }
        }
        Some("ge") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = if a >= b { 1.0 } else { 0.0 };
            }
        }
        Some("eq") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = if (a - b).abs() < 1e-6 { 1.0 } else { 0.0 };
            }
        }
        Some("ne") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = if (a - b).abs() >= 1e-6 { 1.0 } else { 0.0 };
            }
        }
        Some("logical_and") => {
            for (o, (&a, &b)) in output.iter_mut().zip(inputs[0].iter().zip(inputs[1].iter())) {
                *o = if a != 0.0 && b != 0.0 { 1.0 } else { 0.0 };
            }
        }
        other => {
            return Err(format!(
                "compare: unimplemented kind {:?}",
                other,
            ));
        }
    }
    Ok(())
}
"""

# ── Op dispatch: name -> template ───────────────────────────────────────

OP_IMPLS: dict[str, str] = {
    "matmul": OP_MATMUL,
    "element_wise": OP_ELEMENT_WISE,
    "softmax": OP_SOFTMAX,
    "reshape": OP_RESHAPE,
    "transpose": OP_TRANSPOSE,
    "reduce": OP_REDUCE,
    "gather": OP_GATHER,
    "fill": OP_FILL,
    "shape_of": OP_SHAPE_OF,
    "slice": OP_SLICE,
    "unsqueeze": OP_UNSQUEEZE,
    "compare": OP_COMPARE,
    "cache_read": "",
    "cache_write": "",
    # Future: "rms_norm", "layer_norm", "concat", "scan"
}


# ── Main generation function ────────────────────────────────────────────


def emit_rust(
    hal_ir_path: str | Path,
    output_path: str | Path | None = None,
) -> str:
    """Generate ``hal_ops_cpu.rs`` from ``hal_ir.json``.

    Reads the HAL IR JSON, collects all unique op types used in the model,
    and emits a self-contained Rust source file with CPU implementations
    for each op type.

    Args:
        hal_ir_path: Path to ``hal_ir.json``.
        output_path: Where to write the Rust file. If ``None``, writes to
            the same directory as ``hal_ir.json`` with name ``hal_ops_cpu.rs``.

    Returns:
        Absolute path to the written Rust file.
    """
    hal_ir_path = Path(hal_ir_path)
    if not hal_ir_path.exists():
        raise FileNotFoundError(f"hal_ir.json not found: {hal_ir_path}")

    data = json.loads(hal_ir_path.read_text())
    model_name: str = data.get("model_name", "unknown")
    functions: list[dict[str, Any]] = data.get("functions", [])

    # Collect unique op types in use
    op_types_in_use: set[str] = set()
    for fn in functions:
        for op in fn.get("ops", []):
            op_types_in_use.add(op["op"])

    _log.info(
        "EmitRust: model=%s functions=%d unique_ops=%s",
        model_name,
        len(functions),
        sorted(op_types_in_use),
    )

    # ── Assemble Rust source ──────────────────────────────────────────

    parts: list[str] = []

    # Header
    parts.append(HEADER.format(model_name=model_name))

    # Struct
    parts.append(OP_SHAPE_META)

    # BLAS extern
    if "matmul" in op_types_in_use:
        parts.append(BLAS_EXTERN)

    # Stubs (always emitted — harmless if unused)
    parts.append(STUB_CACHE)

    # Per-op implementations
    for op_type in sorted(op_types_in_use):
        if op_type in ("cache_read", "cache_write"):
            continue  # handled by STUB_CACHE above
        impl = OP_IMPLS.get(op_type)
        if impl is None:
            _log.warning("EmitRust: no implementation for op type '%s' — skipping", op_type)
            continue
        parts.append(impl)

    rust_source = "\n".join(parts)

    # ── Write output ──────────────────────────────────────────────────

    if output_path is None:
        output_path = hal_ir_path.parent / "hal_ops_cpu.rs"
    else:
        output_path = Path(output_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rust_source)

    _log.info("EmitRust: wrote %s (%d bytes)", output_path, len(rust_source))
    return str(output_path.resolve())


if __name__ == "__main__":
    import sys

    logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")

    if len(sys.argv) < 2:
        print("Usage: python -m compiler.mlir_dialect.hal_ir.emit_rust <hal_ir.json> [output.rs]")
        sys.exit(1)

    hal_ir_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else None
    path = emit_rust(hal_ir_path, output_path)
    print(f"Generated: {path}")
