"""MLIR text parsing — parse MLIR text into MlirModule.

Section E: Text parsing functions from the original mlir_artifact.py.

Uses a lightweight line-based parser that handles the subset of MLIR
generated by ir_module_to_mlir().  This avoids the overhead of pymlir
for large files and gives direct control over the AST structure.
"""

from __future__ import annotations

import logging
from typing import Any

from compiler.mlir_dialect.mlir_op_types import (
    MlirFunction,
    MlirModule,
    MlirOp,
)

_log = logging.getLogger(__name__)


def _parse_mlir_text(text: str) -> MlirModule:
    """Parse MLIR text into an MlirModule.

    Uses a lightweight line-based parser that handles the subset of MLIR
    generated by ir_module_to_mlir().  This avoids the overhead of pymlir
    for large files and gives us direct control over the AST structure.
    """
    functions: list[MlirFunction] = []
    current_func: MlirFunction | None = None
    ssa_to_name: dict[str, str] = {}  # SSA → weight name
    ssa_types: dict[str, str] = {}  # SSA → MLIR type

    for line in text.splitlines():
        stripped = line.strip()

        # Skip comments and empty lines
        if not stripped or stripped.startswith("//"):
            continue

        # Module / function boundaries
        if stripped == "module {":
            continue
        if stripped == "}":
            if current_func is not None:
                functions.append(current_func)
                current_func = None
            continue

        # Function declaration: func.func @name(...) -> ... {
        if stripped.startswith("func.func @"):
            # Parse function name and signature
            rest = stripped[len("func.func @"):]
            name_end = rest.find("(")
            func_name = rest[:name_end].strip()
            args_str = rest[name_end + 1:rest.find(")")]
            # Parse args: %arg0: tensor<...>, %arg1: tensor<...>
            inputs: list[tuple[str, str]] = []
            for arg in _split_comma(args_str):
                arg = arg.strip()
                if ":" in arg:
                    ssa, tp = arg.split(":", 1)
                    inputs.append((ssa.strip(), tp.strip()))
            # Parse return type: -> type after )
            ret_start = rest.find("->")
            ret_types: list[str] = []
            if ret_start > 0:
                ret_part = rest[ret_start + 2:].strip()
                if ret_part.endswith("{"):
                    ret_part = ret_part[:-1].strip()
                if ret_part and ret_part != "()":
                    # Could be single type or (type1, type2, ...)
                    if ret_part.startswith("("):
                        ret_part = ret_part[1:-1]  # strip parens
                    for tp in _split_comma(ret_part):
                        ret_types.append(tp.strip())
            outputs: list[tuple[str, str, bool]] = [("", tp, False) for tp in ret_types]
            current_func = MlirFunction(name=func_name, inputs=inputs, outputs=outputs)
            ssa_to_name = {}
            ssa_types = {}
            continue

        # Parse func.return: extract output names and match with output types
        if stripped.startswith("func.return"):
            if current_func is not None:
                ret_content = stripped[len("func.return"):].strip()
                if ":" in ret_content:
                    ret_content = ret_content[:ret_content.rfind(":")].strip()
                ret_names = [n.strip() for n in _split_comma(ret_content) if n.strip()]
                if current_func.outputs and ret_names:
                    new_outputs = []
                    for i, name in enumerate(ret_names):
                        tp = current_func.outputs[i][1] if i < len(current_func.outputs) else "tensor<f32>"
                        # Parsed from text MLIR — no consumed_internally info, default False
                        consumed_internally = current_func.outputs[i][2] if len(current_func.outputs[i]) > 2 else False
                        new_outputs.append((name, tp, consumed_internally))
                    if new_outputs:
                        current_func.outputs = new_outputs
            continue

        # Wrapper lines: { or } within function
        if stripped in ("{", "}"):
            continue

        # Parse operations: %r = "dialect.op"(...) {attrs} : (in_types) -> out_type
        if "=" in stripped and "\"" in stripped:
            _parse_mlir_op(
                stripped, current_func, ssa_to_name, ssa_types,
            )

    if current_func is not None:
        functions.append(current_func)

    return MlirModule(functions=functions)


def _parse_mlir_op(
    line: str,
    func: MlirFunction | None,
    ssa_to_name: dict[str, str],
    ssa_types: dict[str, str],
) -> None:
    """Parse a single MLIR operation line."""
    if func is None:
        return

    # Split: %r1, %r2 = "sf.op"(%a, %b) {attr} : (t1, t2) -> (t3, t4)
    eq_idx = line.index("=")
    results_part = line[:eq_idx].strip()
    rest = line[eq_idx + 1:].strip()

    # Parse results (strip % prefix)
    results = [r.strip().lstrip("%") for r in results_part.split(",")]

    # Parse op name
    quote_start = rest.index('"')
    quote_end = rest.index('"', quote_start + 1)
    qualified = rest[quote_start + 1:quote_end]
    dialect, op_name = _split_qualified(qualified)

    # Parse operands: everything between (...) after the op name
    paren_open = rest.index("(", quote_end)
    paren_close = rest.index(")", paren_open)
    operands_str = rest[paren_open + 1:paren_close]
    operands = [o.strip() for o in operands_str.split(",") if o.strip()]

    # Parse attributes: everything between { and } before the :
    attrs: dict[str, Any] = {}
    brace_open = rest.find("{", paren_close)
    colon_idx_for_attrs = rest.find(":", brace_open) if brace_open >= 0 else -1
    if brace_open >= 0 and (colon_idx_for_attrs < 0 or brace_open < colon_idx_for_attrs):
        brace_close = rest.index("}", brace_open)
        attrs_str = rest[brace_open + 1:brace_close]
        attrs = _parse_attrs(attrs_str)

    # Record weight SSA mapping for sf.weight ops
    if qualified == "sf.weight" and "name" in attrs:
        if results:
            ssa_to_name[results[0]] = attrs["name"]

    # Record SSA types and collect input/output type strings
    in_type_strs: list[str] = []
    out_type_strs: list[str] = []
    colon_idx = rest.rfind(":")
    if colon_idx >= 0:
        type_part = rest[colon_idx + 1:].strip()
        arrow_idx = type_part.find("->")
        if arrow_idx >= 0:
            in_types_part = type_part[:arrow_idx].strip()
            if in_types_part.startswith("(") and in_types_part.endswith(")"):
                in_type_strs = _parse_type_list(in_types_part[1:-1])
            elif in_types_part:
                in_type_strs = [in_types_part]
            # Filter out '...' placeholder
            in_type_strs = [t for t in in_type_strs if t != "..."]
            out_types_str = type_part[arrow_idx + 2:].strip()
            out_type_strs = _parse_type_list(out_types_str)
            # Filter out '...' placeholder
            out_type_strs = [t for t in out_type_strs if t != "..."]
        else:
            out_type_strs = [type_part]

        for i, r in enumerate(results):
            if i < len(out_type_strs):
                ssa_types[r] = out_type_strs[i]

    # Resolve operand names from SSA mapping, strip % prefix
    resolved_operands: list[str] = []
    for opnd in operands:
        clean = opnd.lstrip("%")
        if clean in ssa_to_name:
            resolved_operands.append(ssa_to_name[clean])
        else:
            resolved_operands.append(clean)

    func.ops.append(
        MlirOp(
            name=qualified,
            dialect=dialect,
            op_name=op_name,
            operands=resolved_operands,
            results=results,
            attributes=attrs,
            input_types=in_type_strs,
            output_types=out_type_strs,
        )
    )


def _split_qualified(qualified: str) -> tuple[str, str]:
    """Split 'sf.weight' → ('sf', 'weight')."""
    if "." in qualified:
        parts = qualified.split(".", 1)
        return parts[0], parts[1]
    return "sf", qualified


def _split_comma(text: str) -> list[str]:
    """Split by commas, respecting nested angle brackets."""
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in text:
        if ch in "<(":
            depth += 1
        elif ch in ">)":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current).strip())
    return parts


def _parse_attrs(attrs_str: str) -> dict[str, Any]:
    """Parse MLIR attribute string like 'dim = 0, name = "foo"'."""
    result: dict[str, Any] = {}
    if not attrs_str.strip():
        return result

    parts = _split_attrs(attrs_str)
    for part in parts:
        part = part.strip()
        if "=" not in part:
            continue
        k, v = part.split("=", 1)
        k = k.strip()
        # Strip quotes from attribute keys (emitters quote them)
        if k.startswith('"') and k.endswith('"'):
            k = k[1:-1]
        v = v.strip()
        # Parse value
        if v == "true":
            result[k] = True
        elif v == "false":
            result[k] = False
        elif v == "none":
            result[k] = None
        elif v.startswith('"') and v.endswith('"'):
            raw = v[1:-1]
            if " : " in raw:
                raw = raw.split(" : ")[0]
                try:
                    result[k] = int(raw)
                except ValueError:
                    try:
                        result[k] = float(raw)
                    except ValueError:
                        result[k] = raw
            else:
                result[k] = raw
        elif v.startswith("[") and v.endswith("]"):
            inner = v[1:-1]
            items = _split_comma(inner)
            result[k] = [_parse_attr_value(item.strip()) for item in items if item.strip()]
        else:
            raw = v
            if " : " in v:
                raw = v.split(" : ")[0]
            try:
                result[k] = int(raw)
            except ValueError:
                try:
                    result[k] = float(raw)
                except ValueError:
                    result[k] = raw
    return result


def _split_attrs(text: str) -> list[str]:
    """Split attribute string respecting nested brackets and quotes."""
    parts: list[str] = []
    depth = 0
    in_quote = False
    current: list[str] = []
    for ch in text:
        if ch == '"':
            in_quote = not in_quote
        if not in_quote:
            if ch in "[{(":
                depth += 1
            elif ch in "]})":
                depth -= 1
        if ch == "," and depth == 0 and not in_quote:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current).strip())
    return parts


def _parse_attr_value(v: str) -> Any:
    """Parse a single attribute value, stripping MLIR type annotations."""
    v = v.strip()
    if v == "true":
        return True
    if v == "false":
        return False
    if v == "none":
        return None
    if v.startswith('"') and v.endswith('"'):
        raw = v[1:-1]
        if " : " in raw:
            raw = raw.split(" : ")[0]
            try:
                return int(raw)
            except ValueError:
                try:
                    return float(raw)
                except ValueError:
                    return raw
        return raw
    if " : " in v:
        v = v.split(" : ")[0]
    try:
        return int(v)
    except ValueError:
        try:
            return float(v)
        except ValueError:
            return v


def _parse_type_list(text: str) -> list[str]:
    """Parse a comma-separated list of MLIR types, respecting angle brackets."""
    text = text.strip()
    if text.startswith("(") and text.endswith(")"):
        text = text[1:-1]
    if not text:
        return []
    return [t.strip() for t in _split_comma(text)]
