// RUN: %sf-opt --sf-chain-wrapper --sf-lower-to-linalg %s \
// RUN:   | %mlir-opt --one-shot-bufferize="bufferize-function-boundaries" \
// RUN:       --convert-linalg-to-loops --convert-scf-to-cf \
// RUN:       --convert-to-llvm \
// RUN:   | FileCheck %s
//
// Verify chain-wrapper -> linalg lowering -> bufferize -> LLVM dialect
// produces structurally correct LLVM IR for a multi-function module.
// Tests that func @main (generated by chain-wrapper) survives bufferization
// and LLVM conversion without internal assertion failures or type mismatches.
//
// exec_plan_data (derived from ExecutionPlan proto):
//   num_steps=2, num_global=3
//   step0: 3 GLOBAL_INPUT -> input_ids, emb_weight, rms_weight
//   step1: 2 STEP_OUTPUT -> hidden_state (step0.out0), rms_weight (step0.out1)

module attributes {sf.chain_order = ["main_0", "main_1"],
                   sf.exec_plan_data = [2, 3,
                     3, 0, 0, 0, 0, 1, 0, 0, 2, 0,
                     2, 1, 0, 0, 1, 0, 1]} {
  func.func @main_0(%arg0: tensor<2x4xi64>, %arg1: tensor<100x64xf32>,
                      %arg2: tensor<64xf32>)
      -> (tensor<2x4x64xf32>, tensor<64xf32>)
      attributes {sf.weight_names = ["tok_embed_weight", "rms_weight"]} {
    %0 = "sf.embedding"(%arg1, %arg0) {num_buckets = 100 : i64}
        : (tensor<100x64xf32>, tensor<2x4xi64>) -> tensor<2x4x64xf32>
    return %0, %arg2 : tensor<2x4x64xf32>, tensor<64xf32>
  }
  func.func @main_1(%arg0: tensor<2x4x64xf32>, %arg1: tensor<64xf32>)
      -> tensor<2x4x64xf32>
      attributes {sf.weight_names = ["rms_weight"]} {
    %0 = "sf.rms_norm"(%arg0, %arg1)
        : (tensor<2x4x64xf32>, tensor<64xf32>) -> tensor<2x4x64xf32>
    return %0 : tensor<2x4x64xf32>
  }
}

// CHECK:      llvm.func @main_0
// CHECK:      llvm.func @main_1
// CHECK:      llvm.func @main(
// CHECK:        llvm.call @main_0(
// CHECK:        llvm.call @main_1(
// CHECK:        llvm.return
