//! Pure-Rust HAL backend — uses generated ``hal_ops_cpu`` functions.
//!
//! ``HalRustExecutable`` dispatches ``traits::Executable::execute()``
//! by op_name to the corresponding ``*_cpu`` function generated by
//! EmitRust.
//!
//! This module is compiled only when ``feature = "hal-rust"`` is enabled
//! (see Cargo.toml).

pub mod executable;
