"""HAL IR Builder — builds the HAL IR structure from normalized MLIR.

Usage::

    builder = HalIRBuilder()
    builder.load_mlir(mlir_text)
    builder.load_metadata(metadata_dict)
    result = builder.build()  # returns JSON dict + stores MlirModule internally
"""

from __future__ import annotations

import logging
import re
from typing import Any

from compiler.hal.op_lowering import (
    infer_dtype_from_type,
    lower_op,
    parse_sf_op_name,
    shape_from_type,
    strip_mlir_quotes,
)
from compiler.hal.ssa_tracker import SSATracker
from compiler.artifact import MlirFunction, MlirModule, MlirOp  # type: ignore[attr-defined]
from compiler.backend.compile_utils import _setup_mlir_path

_log = logging.getLogger(__name__)


# ── HAL IR Builder ──────────────────────────────────────────────────


class HalIRBuilder:
    """Builds the HAL IR structure from a normalized MLIR module.

    Usage::

        builder = HalIRBuilder()
        builder.load_mlir(mlir_text)
        builder.load_metadata(metadata_dict)
        result = builder.build()
    """

    def __init__(self) -> None:
        self._model_name = "model"
        self._mlir_text: str = ""
        self._metadata: dict[str, Any] = {}
        self._functions: list[MlirFunction] = []
        self._mlir_module: MlirModule | None = None
        self._cache_policy: dict[str, Any] = {}
        self._weight_classification: dict[str, Any] = {}
        self._hf_key_map: dict[str, str] = {}
        self._mlir_text_output: str = ""

    def load_mlir(self, mlir_text: str) -> None:
        """Parse and store the MLIR text."""
        self._mlir_text = mlir_text

    def load_metadata(self, metadata: dict[str, Any]) -> None:
        """Load compilation metadata (from metadata.json)."""
        self._metadata = metadata
        self._cache_policy = metadata.get("cache_policy", {})
        self._weight_classification = metadata.get("weight_classification", {})
        self._hf_key_map = metadata.get("hf_key_map", {})

    def set_model_name(self, name: str) -> None:
        self._model_name = name

    def build(self) -> dict[str, Any]:
        """Build the complete HAL IR structure.

        Returns a dict ready to be serialized as JSON (backward-compatible
        with the Rust runtime).  The internal :class:`MlirModule` is also
        stored as ``self._mlir_module``.
        """
        _setup_mlir_path()
        import mlir.ir as ir

        ctx = ir.Context()
        ctx.allow_unregistered_dialects = True
        try:
            from mlir_sf._mlir_libs._sfDialectsNanobind import sf

            sf.register_dialects(ctx._CAPIPtr, load=True)
        except ImportError:
            _log.warning("SF dialect bindings not available; "
                         "proceeding without registration")

        with ctx, ir.Location.unknown(ctx):
            module = ir.Module.parse(self._mlir_text, ctx)
            self._build_from_module(module)

        # Build MlirModule (public for API consumers)
        self._mlir_module = MlirModule(
            functions=self._functions,
            metadata={
                "model_name": self._model_name,
                "num_functions": len(self._functions),
            },
        )

        # Generate MLIR text from the built MlirModule
        try:
            from compiler.artifact import mlir_module_to_text
            self._mlir_text_output = mlir_module_to_text(self._mlir_module)
        except Exception as e:
            _log.warning("Failed to generate HAL IR MLIR text: %s", e)
            self._mlir_text_output = ""

        # Convert to backward-compatible JSON dict
        return self._to_json(self._mlir_module)

    @property
    def mlir_text(self) -> str:
        """Get the HAL IR MLIR text (generated by build())."""
        return self._mlir_text_output

    # ── Module traversal ─────────────────────────────────────────────

    def _build_from_module(self, module: Any) -> None:
        """Walk the module and build function entries."""
        for op in module.operation.regions[0].blocks[0]:
            op_name = str(op.operation.name)
            if op_name == "func.func":
                func_entry = self._build_function(op)
                self._functions.append(func_entry)

    @staticmethod
    def _extract_layer(func_name: str) -> int | None:
        """Extract layer number from function name pattern like main_1a, main_2b."""
        m = re.search(r"main_(\d+)", func_name)
        if m:
            return int(m.group(1))
        return None

    def _get_weight_classification(
        self, func_name: str
    ) -> dict[str, list[str]]:
        """Return the weight classification for a function (empty if missing)."""
        return self._weight_classification.get(func_name, {  # type: ignore[no-any-return]
            "params": [],
            "constants": [],
        })

    # ── Function building ────────────────────────────────────────────

    def _build_function(self, func_op: Any) -> MlirFunction:
        """Process a single func.func op and return its :class:`MlirFunction`."""
        # Get function name (strip MLIR string quotes from StringAttr)
        func_name = strip_mlir_quotes(
            str(func_op.attributes.get("sym_name", "unknown"))
        )
        layer_idx = self._extract_layer(func_name)
        _ = str(func_op.attributes.get("function_type", ""))

        # Get operands and results
        func_region = func_op.regions[0]
        func_block = func_region.blocks[0]

        # ── Inputs from block args ──────────────────────────────
        inputs: list[tuple[str, str]] = []
        weight_class = self._get_weight_classification(func_name)
        param_names = weight_class.get("params", [])
        const_names = weight_class.get("constants", [])

        ssa = SSATracker()
        for i, arg in enumerate(func_block.arguments):
            arg_name = f"%arg{i}"
            ssa.register_arg(arg, arg_name)
            arg_type = str(arg.type) if hasattr(arg, "type") else "unknown"
            inputs.append((arg_name, arg_type))

        # ── Detect consumed_internally patterns ─────────────────
        consumed_internally: list[int] = []
        is_kv_func_a = bool(re.match(r"main_\d+a$", func_name))
        is_kv_func_b = bool(re.match(r"main_\d+b$", func_name))
        is_embed_func = func_name == "main_0"

        if is_kv_func_a:
            consumed_internally = [1, 2]
        elif is_embed_func:
            consumed_internally = [13]

        # ── Walk ops ────────────────────────────────────────────
        ops: list[MlirOp] = []
        weights: list[dict[str, Any]] = []
        constants: list[dict[str, Any]] = []
        weight_index: dict[str, int] = {}

        for inner_op in func_block:
            raw_name = str(inner_op.operation.name)
            op_name = parse_sf_op_name(raw_name)

            result_hal = lower_op(
                inner_op, op_name, ssa, weights, constants,
                weight_index, param_names, const_names,
            )
            if result_hal is not None:
                ops.append(result_hal)

        # ── Handle consumed_internally: insert cache_write/cache_read ──
        if is_kv_func_a and consumed_internally:
            self._add_cache_ops(
                ops, func_name, layer_idx, consumed_internally, is_kv_func_b,
            )
        if is_kv_func_b:
            self._add_cache_ops(ops, func_name, layer_idx, [], True)

        # ── Determine outputs ───────────────────────────────────
        return_op = None
        for inner_op in func_block:
            if str(inner_op.operation.name) in ("func.return", "return"):
                return_op = inner_op
                break

        outputs: list[tuple[str, str, bool]] = []
        if return_op is not None:
            for i, operand in enumerate(return_op.operands):
                ot = str(operand.type) if hasattr(operand, "type") else "unknown"
                is_consumed = i in consumed_internally
                outputs.append((ssa.lookup(operand), ot, is_consumed))

        # ── Build weight input mapping ───────────────────────────
        weight_inputs: dict[str, str] = {}
        w_idx = 0
        for arg_name, arg_type in inputs:
            shape = shape_from_type(arg_type)
            is_dyn = any(d == "?" or d == -1 or d == "-1" for d in shape)
            is_scalar = bool(shape) and all(
                (isinstance(d, str) and d in ("1", "?"))
                or (isinstance(d, int) and d == 1)
                for d in shape
            )
            if not is_dyn and not is_scalar and w_idx < len(param_names):
                weight_inputs[arg_name] = param_names[w_idx]
                w_idx += 1

        # ── Inject shape_of ops for wire input dynamic dims ─────
        input_dicts = [
            {"name": name, "shape": shape_from_type(tp)}
            for name, tp in inputs
        ]
        self._inject_shape_of_ops(input_dicts, weight_inputs, ops)

        # ── Build MlirFunction ──────────────────────────────────
        func = MlirFunction(
            name=func_name,
            inputs=inputs,
            outputs=outputs,
            ops=ops,
            weights={
                "entries": weights,
                "weight_inputs": weight_inputs,
            },
            param_weight_names=set(param_names),
            const_weight_names=set(const_names),
        )

        return func

    # ── Shape-of injection ───────────────────────────────────────────

    def _inject_shape_of_ops(
        self,
        inputs: list[dict[str, Any]],
        weight_inputs: dict[str, str],
        ops: list[MlirOp],
    ) -> None:
        """Inject shape_of ops for wire input dims and wire them to reshape/fill."""
        dyn_set = {"?", -1, "-1"}
        wire_input = None
        best_score = -999
        for inp in inputs:
            shape = inp["shape"]
            has_dyn = any(d in dyn_set for d in shape)
            is_weight = inp["name"] in weight_inputs
            rank = len(shape)
            if has_dyn and rank >= 2 and not is_weight:
                dyn_count = sum(1 for d in shape if d in dyn_set)
                score = -rank * 10 + dyn_count
                if score > best_score:
                    best_score = score
                    wire_input = inp

        if wire_input is None:
            return

        shape_of_ops: list[MlirOp] = []
        wire_name = wire_input["name"].replace("%", "")
        for dim_idx, dim_val in enumerate(wire_input["shape"]):
            if dim_val in ("?", -1, "-1"):
                out_name = f"%shape_of_{wire_name}_dim{dim_idx}"
                shape_of_ops.append(MlirOp(
                    name="hal.shape_of", dialect="hal", op_name="shape_of",
                    operands=[wire_input["name"]],
                    results=[out_name],
                    attributes={"dim": dim_idx},
                ))

        if not shape_of_ops:
            return

        for i, sop in enumerate(shape_of_ops):
            ops.insert(i, sop)

        shape_of_names = [op.results[0] for op in shape_of_ops]
        for op in ops:
            if op.op_name != "reshape":
                continue
            shape = op.attributes.get("shape")
            if shape is None:
                continue
            if len(shape) <= 2:
                continue
            num_dyn = sum(1 for d in shape if d in dyn_set)
            if num_dyn > 0 and len(op.operands) <= 1:
                n = min(num_dyn, len(shape_of_names))
                op.operands.extend(shape_of_names[:n])

    # ── Cache op injection ───────────────────────────────────────────

    def _add_cache_ops(
        self,
        ops: list[MlirOp],
        func_name: str,
        layer_idx: int | None,
        consumed_indices: list[int],
        is_b_func: bool,
    ) -> None:
        """Insert cache_write and cache_read ops for consumed_internally outputs."""
        if layer_idx is None:
            return

        if is_b_func:
            cache_read_entry = MlirOp(
                name="hal.cache_read", dialect="hal", op_name="cache_read",
                operands=["%block_table"],
                results=[f"%cache_k_{layer_idx}", f"%cache_v_{layer_idx}"],
                attributes={"layer": layer_idx},
            )
            ops.insert(0, cache_read_entry)
        else:
            cache_write_entry = MlirOp(
                name="hal.cache_write", dialect="hal", op_name="cache_write",
                operands=[],
                results=[],
                attributes={"layer": layer_idx},
            )
            ops.append(cache_write_entry)

    # ── JSON conversion (backward compat for Rust runtime) ───────────

    def _to_json(self, mlir_module: MlirModule) -> dict[str, Any]:
        """Convert :class:`MlirModule` to backward-compatible JSON dict."""
        functions_json = []
        for func in mlir_module.functions:
            layer_idx = self._extract_layer(func.name)

            # Convert inputs: (ssa_name, mlir_type) → {name, shape, dtype}
            inputs_json: list[dict[str, Any]] = []
            for ssa_name, mlir_type in func.inputs:
                dtype = infer_dtype_from_type(mlir_type)
                shape = shape_from_type(mlir_type)
                inputs_json.append({
                    "name": ssa_name,
                    "shape": shape,
                    "dtype": dtype,
                })

            # Convert outputs: (ssa_name, mlir_type, consumed) → dict
            outputs_json: list[dict[str, Any]] = []
            for ssa_name, mlir_type, consumed in func.outputs:
                dtype = infer_dtype_from_type(mlir_type)
                shape = shape_from_type(mlir_type)
                entry: dict[str, Any] = {
                    "name": ssa_name,
                    "shape": shape,
                    "dtype": dtype,
                }
                if consumed:
                    entry["consumed_internally"] = True
                outputs_json.append(entry)

            weight_entries = func.weights.get("entries", [])
            weight_inputs = func.weights.get("weight_inputs", {})

            # Convert ops: MlirOp → dict
            ops_json: list[dict[str, Any]] = []
            for op in func.ops:
                op_dict: dict[str, Any] = {
                    "op": op.op_name,
                    "inputs": op.operands,
                    "outputs": op.results,
                }
                op_dict.update(op.attributes)
                if op.input_types:
                    op_dict["input_dtypes"] = [
                        infer_dtype_from_type(t) for t in op.input_types
                    ]
                if op.output_types:
                    op_dict["output_dtypes"] = [
                        infer_dtype_from_type(t) for t in op.output_types
                    ]
                ops_json.append(op_dict)

            # Build function entry
            func_entry: dict[str, Any] = {
                "name": func.name,
                "layer": layer_idx,
                "inputs": inputs_json,
                "outputs": outputs_json,
                "weights": weight_entries,
                "constants": [],
                "weight_inputs": weight_inputs,
                "ops": ops_json,
            }

            is_kv_a = bool(re.match(r"main_\d+a$", func.name))
            is_kv_b = bool(re.match(r"main_\d+b$", func.name))
            if is_kv_a or is_kv_b:
                func_entry["block_table"] = True

            functions_json.append(func_entry)

        return {
            "model_name": self._model_name,
            "num_functions": len(functions_json),
            "functions": functions_json,
        }
