"""Per-function 4-gate precision test against golden outputs.

For each config case (seq1/2/6/32), loads golden .npz files generated by
``generate_golden_outputs.py``, calls each compiled function via ctypes in
topological SSA order, and compares every output against its golden using a
4-gate precision check.

**4 Gates:**
1.  **cos gate**: cosine similarity ≥ ``min_cos`` (default 0.9999)
2.  **zero-mean gate**: mean(|diff|) / max(mean(|expected|), 1e-8) < 0.01
3.  **outliers gate**: max(|diff|) / max(std(expected), 1e-8) < 10
4.  **top-N gate**: Jaccard overlap of top-10 indices ≥ 0.5

**Usage**::

    # Run all cases — ~64 tests (4 cases × 16 functions).  Each test's
    # class-level 120s timeout covers the class-scoped fixture (weight
    # loading + golden loading).
    pytest compiler/tests/test_per_function_cos.py -v

    # Stop at first failure (use pytest's built-in -x flag)
    pytest compiler/tests/test_per_function_cos.py -v -x

    # Filter by case or function
    pytest compiler/tests/test_per_function_cos.py -v -k "seq6"
    pytest compiler/tests/test_per_function_cos.py -v -k "main_3"

**No special treatment for seq=1** — all cases use the same 4-gate thresholds.
The config cases' fixed ``tokens`` (used to generate the goldens) are honored
by the harness, and the 4-gate check degrades gracefully for 1-element
outputs (scalar passthroughs in main_0).
"""

from __future__ import annotations

import ctypes
import json
import os
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pytest

# ── Path setup ──────────────────────────────────────────────────────

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from compiler.dylib_ffi import (  # noqa: E402
    DEFAULT_SRET_SIZE,
    compute_sret_size,
    load_graph_from_proto,
)
from compiler.tests.generate_golden_outputs import (  # noqa: E402
    build_input_arrays,
    call_ciface_function,
    generate_tokens,
    load_config,
    load_safetensors_weights,
)
from compiler.tests.golden_io import load_npz  # noqa: E402

# ── Constants ───────────────────────────────────────────────────────

GOLDEN_BASE = ROOT / "tests" / "data" / "golden" / "npy" / "opt_125m"
CONFIG_PATH = GOLDEN_BASE / "configs.json"
TOP_N: int = 10


# ── Golden auto-generation ───────────────────────────────────────────


def _ensure_golden_exists(
    config: dict[str, Any],
    golden_base: Path,
    metadata: dict[str, Any],
) -> None:
    """Auto-generate HF golden .npz files if they don't exist.

    Called once per test session (class-scoped fixture).  Checks whether
    the first expected .npz file exists; if not, runs the HF golden
    generator to populate ``golden_base``.
    """
    cases = config.get("cases", [])
    chain_order = metadata.get("chain_order", [])
    if not cases or not chain_order:
        return

    first_case = cases[0]["name"]
    first_func = chain_order[0]
    first_npz = golden_base / first_case / f"func_{first_func}_output.npz"

    if first_npz.is_file():
        return  # golden already exists

    import subprocess  # noqa: E402
    import sys  # noqa: E402

    print(
        f"\n{'='*60}\n"
        f"Golden .npz files not found at {golden_base}\n"
        f"Auto-generating from HuggingFace reference (one-time setup)...\n"
        f"{'='*60}\n",
        file=sys.stderr,
    )
    result = subprocess.run(
        [
            sys.executable,
            str(ROOT / "compiler" / "tests" / "generate_golden_outputs.py"),
            "--config", str(golden_base / "configs.json"),
            "--output", str(golden_base),
            "--hf-golden",
        ],
        capture_output=False,
        env={**os.environ, "HF_ENDPOINT": "https://hf-mirror.com"},
    )
    if result.returncode != 0:
        pytest.fail(f"Golden generation failed with exit code {result.returncode}")


# ── 4-Gate precision check ──────────────────────────────────────────


def _cosine_similarity(a: np.ndarray[Any, Any], b: np.ndarray[Any, Any]) -> float:
    """Compute cosine similarity between two float32 arrays (via float64)."""
    a_f = a.ravel().astype(np.float64)
    b_f = b.ravel().astype(np.float64)
    denom = np.linalg.norm(a_f) * np.linalg.norm(b_f) + 1e-12
    return float(np.dot(a_f, b_f) / denom)


def check_4_gate(
    actual: np.ndarray[Any, Any],
    expected: np.ndarray[Any, Any],
    min_cos: float = 0.9999,
) -> tuple[bool, dict[str, Any]]:
    """Run 4-gate precision check on ``actual`` vs ``expected`` tensors.

    Args:
        actual: Computed output (float32).
        expected: Golden reference output (float32).
        min_cos: Minimum cosine similarity threshold.

    Returns:
        ``(passed, details)`` where ``passed`` is True when ALL gates pass,
        and ``details`` is a dict with per-gate results and diagnostic values.
    """
    if actual.shape != expected.shape:
        return False, {
            "cos": 0.0,
            "cos_ok": False,
            "mean_rel_err": float("inf"),
            "mean_rel_err_ok": False,
            "max_outlier": float("inf"),
            "max_outlier_ok": False,
            "top_n_jaccard": 0.0,
            "top_n_jaccard_ok": False,
            "error": f"Shape mismatch: actual {actual.shape}, expected {expected.shape}",
        }

    actual_f = actual.astype(np.float64).ravel()
    expected_f = expected.astype(np.float64).ravel()
    diff = actual_f - expected_f
    abs_diff = np.abs(diff)

    # Gate 1: cosine similarity
    denom = np.linalg.norm(actual_f) * np.linalg.norm(expected_f) + 1e-12
    cos = float(np.dot(actual_f, expected_f) / denom)
    cos_ok = bool(cos >= min_cos)

    # Gate 2: zero-mean — relative mean absolute error
    expected_mean_abs = float(np.mean(np.abs(expected_f)))
    mean_abs_error = float(np.mean(abs_diff)) if abs_diff.size > 0 else 0.0
    mean_rel_err = mean_abs_error / max(expected_mean_abs, 1e-8)
    mean_rel_err_ok = bool(mean_rel_err < 0.01)

    # Gate 3: no extreme outliers relative to signal std
    expected_std = float(np.std(expected_f))
    max_outlier = float(np.max(abs_diff)) if abs_diff.size > 0 else 0.0
    max_outlier_norm = max_outlier / max(expected_std, 1e-8)
    max_outlier_ok = bool(max_outlier_norm < 10)

    # Gate 4: top-N overlap (Jaccard).  Small tensors (e.g. the 1-element
    # scalar passthrough outputs of main_0) use k = min(TOP_N, size) so
    # argpartition never receives an out-of-bounds kth.
    k = min(TOP_N, int(actual_f.size))
    top_k_actual = {int(i) for i in np.argpartition(np.abs(actual_f), -k)[-k:]}
    top_k_expected = {int(i) for i in np.argpartition(np.abs(expected_f), -k)[-k:]}
    intersection = len(top_k_actual & top_k_expected)
    union = len(top_k_actual | top_k_expected)
    top_n_jaccard = intersection / max(union, 1)
    top_n_jaccard_ok = bool(top_n_jaccard >= 0.5)

    passed = bool(cos_ok and mean_rel_err_ok and max_outlier_ok and top_n_jaccard_ok)

    return passed, {
        "cos": cos,
        "cos_ok": cos_ok,
        "mean_rel_err": mean_rel_err,
        "mean_rel_err_ok": mean_rel_err_ok,
        "max_outlier": max_outlier,
        "max_outlier_norm": max_outlier_norm,
        "max_outlier_ok": max_outlier_ok,
        "top_n_jaccard": top_n_jaccard,
        "top_n_jaccard_ok": top_n_jaccard_ok,
    }


def _format_gate_details(details: dict[str, Any]) -> str:
    """Format gate check details as a multi-line error message."""
    parts: list[str] = []
    if "error" in details:
        parts.append(f"    ERROR: {details['error']}")
        return "\n".join(parts)

    parts.append(f"    cos          = {details['cos']:.10f}  [OK={details['cos_ok']}]")
    parts.append(
        f"    mean_rel_err = {details['mean_rel_err']:.6e}  [OK={details['mean_rel_err_ok']}]"
    )
    parts.append(
        f"    max_outlier  = {details['max_outlier']:.6e} "
        f"(norm={details['max_outlier_norm']:.2f})  [OK={details['max_outlier_ok']}]"
    )
    parts.append(
        f"    top-{TOP_N} jaccard = {details['top_n_jaccard']:.3f}  "
        f"[OK={details['top_n_jaccard_ok']}]"
    )
    return "\n".join(parts)


# ── Test parametrization ────────────────────────────────────────────


def _read_config_cases() -> list[tuple[str, str]]:
    """Read configs.json at import time to build pytest parametrize args.

    Returns a list of ``(case_name, func_symbol)`` tuples for each
    (config case × chain_order function) combination.
    """
    if not CONFIG_PATH.is_file():
        # Fallback: hardcoded defaults for test collection without golden data
        cases = [
            {"name": "seq1"}, {"name": "seq2"}, {"name": "seq6"}, {"name": "seq32"},
        ]
        chain_order = [f"main_{i}" for i in range(16)]
    else:
        with open(CONFIG_PATH) as f:
            config = json.load(f)
        cases = config.get("cases", [])
        # chain_order lives in metadata.json next to the dylib
        chain_order = config.get("_chain_order", [])
        if not chain_order:
            # Try to read from metadata.json directly
            dylib_dir = Path(config.get("_resolved_dylib_path", "")).parent
            metadata_path = dylib_dir / "metadata.json"
            if metadata_path.is_file():
                with open(metadata_path) as f:
                    chain_order = json.load(f).get("chain_order", [])
        if not chain_order:
            chain_order = [f"main_{i}" for i in range(16)]

    test_cases: list[tuple[str, str]] = []
    for case in cases:
        case_name = case["name"]
        for func_symbol in chain_order:
            test_cases.append((case_name, func_symbol))
    return test_cases


# ── Test class ──────────────────────────────────────────────────────


@pytest.mark.timeout(120)  # per-test timeout: SSA chain + golden compare
class TestPerFunctionCos:
    """Per-function 4-gate precision test against golden .npz outputs.

    The class-scoped fixture loads the dylib, compute graph, weights,
    config, and all golden .npz files once.  Each parametrized test
    reruns the SSA chain up to its target function and compares against
    the corresponding golden output.
    """

    @pytest.fixture(scope="class")
    def golden_data(self) -> dict[str, Any]:
        """Load all shared data once for the test class.

        Returns a dict with keys: ``lib``, ``config``, ``compute_graph``,
        ``weights``, ``chain_order``, ``func_index_map``, ``case_golden``
        (nested dict: case_name → func_symbol → dict of loaded npz tensors),
        ``case_configs`` (list of case dicts).
        """
        config = load_config(str(CONFIG_PATH))

        dylib_path = config["_resolved_dylib_path"]
        metadata = config["_metadata"]

        # Store chain_order and cases in config for parametrization
        chain_order: list[str] = metadata.get("chain_order", [])
        config["_chain_order"] = chain_order
        config["cases"] = config.get("cases", [])

        # Load dylib
        lib = ctypes.CDLL(dylib_path)

        # Load compute graph from embedded proto
        compute_graph = load_graph_from_proto(lib)
        functions = compute_graph["functions"]

        # Build function index map: symbol → func_index
        func_index_map: dict[str, int] = {}
        for fi, fg in enumerate(functions):
            # symbol from proto is like "_mlir_ciface_main_0" — strip prefix
            symbol = fg["symbol"].replace("_mlir_ciface_", "")
            func_index_map[symbol] = fi

        # Load weights
        weights = load_safetensors_weights(metadata)

        # Auto-generate golden .npz files if missing
        _ensure_golden_exists(config, GOLDEN_BASE, metadata)

        # Load all golden .npz files
        case_golden: dict[str, dict[str, dict[str, np.ndarray[Any, Any]]]] = {}
        for case in config["cases"]:
            case_name = case["name"]
            case_dir = GOLDEN_BASE / case_name
            case_golden[case_name] = {}
            for func_symbol in chain_order:
                npz_path = case_dir / f"func_{func_symbol}_output.npz"
                if npz_path.is_file():
                    case_golden[case_name][func_symbol] = load_npz(npz_path)

        return {
            "lib": lib,
            "config": config,
            "compute_graph": compute_graph,
            "weights": weights,
            "chain_order": chain_order,
            "func_index_map": func_index_map,
            "case_golden": case_golden,
            "case_configs": config["cases"],
        }

    def _get_session_state(
        self,
        golden_data: dict[str, Any],
        case_dict: dict[str, Any],
    ) -> dict[str, Any]:
        """Run SSA chain up to a given position and return session state.

        Session state: token_ids, input_ids.

        The golden .npz files are generated with the config case's FIXED
        ``tokens`` (when present — see generate_golden_outputs.py); the
        harness must use the same tokens, not a fresh random draw, or the
        comparison is input-mismatched and fails spuriously.
        """
        seq_len: int = case_dict["seq_len"]
        batch_size: int = case_dict.get("batch_size", 1)
        if "tokens" in case_dict:
            token_ids = np.array(case_dict["tokens"], dtype=np.int64)
        else:
            token_ids = generate_tokens(seq_len, batch_size=batch_size)
        input_ids = token_ids.reshape(batch_size, seq_len).astype(np.int64)
        return {
            "token_ids": token_ids,
            "input_ids": input_ids,
        }

    def _run_chain_up_to(
        self,
        golden_data: dict[str, Any],
        session: dict[str, Any],
        target_symbol: str,
    ) -> list[np.ndarray[Any, Any]]:
        """Run all functions in chain_order up to and including target_symbol.

        Returns the FULL outputs list of the target function (not just the last
        element).  The caller indexes by the golden key's output index (e.g.
        ``output_12`` → ``outputs[12]``, ``output_0`` → ``outputs[0]``).
        This correctly handles main_0 (211 outputs, embedding at output_12)
        vs. main_1..main_15 (1 output each at output_0).
        """
        lib = golden_data["lib"]
        compute_graph = golden_data["compute_graph"]
        weights = golden_data["weights"]
        chain_order: list[str] = golden_data["chain_order"]
        func_index_map: dict[str, int] = golden_data["func_index_map"]
        functions = compute_graph["functions"]
        input_ids = session["input_ids"]

        func_outputs: dict[int, list[np.ndarray[Any, Any]]] = {}

        for func_symbol in chain_order:
            fi = func_index_map.get(func_symbol)
            if fi is None:
                continue

            fg = functions[fi]

            # Build input arrays from SSA outputs + weights + global input
            input_arrays = build_input_arrays(
                fg, func_outputs, weights, input_ids,
            )

            # Compute sret size
            sret_size = compute_sret_size(fg["outputs"], floor=DEFAULT_SRET_SIZE)

            # Call function
            outputs = call_ciface_function(
                lib, func_symbol, input_arrays, fg["outputs"], sret_size,
            )
            func_outputs[fi] = outputs

            if func_symbol == target_symbol:
                return outputs

        raise RuntimeError(
            f"Target symbol '{target_symbol}' not found in chain_order"
        )

    @pytest.mark.parametrize(
        "case_name,func_symbol",
        _read_config_cases(),
    )
    def test_function_matches_golden(
        self,
        golden_data: dict[str, Any],
        case_name: str,
        func_symbol: str,
    ) -> None:
        """Test that ``func_symbol`` outputs match golden for ``case_name``.

        1. Run the SSA chain up to ``func_symbol``.
        2. Load the corresponding golden .npz file.
        3. Compare every output via the 4-gate precision check.
        4. Assert all gates pass with a descriptive error message.
        """
        # Look up case config
        case_dict: dict[str, Any] | None = None
        for c in golden_data["case_configs"]:
            if c["name"] == case_name:
                case_dict = c
                break
        assert case_dict is not None, f"Unknown case: {case_name}"

        # Look up golden tensors
        case_golden = golden_data["case_golden"]
        case_dict_data = case_golden.get(case_name, {})
        if func_symbol not in case_dict_data:
            pytest.skip(
                f"Golden .npz for case={case_name}, func={func_symbol} not found"
            )
        golden_tensors = case_dict_data[func_symbol]

        # Create session (token IDs for this case)
        session = self._get_session_state(golden_data, case_dict)

        # Run SSA chain up to target function — get ALL outputs
        all_outputs = self._run_chain_up_to(golden_data, session, func_symbol)

        # Compare the golden output against the corresponding dylib output.
        # The golden .npz may have many keys (main_0: 211 keys) or just one
        # (main_1..main_15: output_0).  We sort keys numerically and take the
        # LAST one; its numeric suffix determines which dylib output index to
        # compare against:
        #   main_0 HF golden:  key="output_12" → index 12 → outputs[12] (embedding)
        #   main_0 dylib golden: key="output_210" → index 210 → outputs[210] (weight)
        #   main_1..main_15:     key="output_0" → index 0 → outputs[0]
        golden_keys = sorted(golden_tensors.keys(), key=lambda k: int(k.split("_")[1]))
        if not golden_keys:
            pytest.fail(
                f"No golden tensors for case={case_name}, func={func_symbol}"
            )

        golden_key = golden_keys[-1]
        golden_idx = int(golden_key.split("_")[1])
        expected = golden_tensors[golden_key]
        actual = all_outputs[golden_idx]

        passed, details = check_4_gate(actual, expected, min_cos=0.9999)

        if not passed:
            fail_msg = (
                f"\nFunction '{func_symbol}' FAILED 4-gate check "
                f"(case={case_name}, seq_len={case_dict['seq_len']}):\n"
                f"{_format_gate_details(details)}"
            )
            pytest.fail(fail_msg)
